### PR TITLE
Added redirection action

### PR DESCRIPTION
**Pull request by squallstar**
- Added redirection action

Img

### CODE REVIEW

**Comment by ibroom** [comment]
@tonytlwu UI comments without really understanding the spec or ideas https://docs.google.com/a/weboo.biz/presentation/d/1jHm2D8ZcIMD3yJJXTEpi9sPi7CdzqHwkutqdrvgBc7o/edit?usp=sharing

**Comment by tonytlwu** [comment]
@ibroom Thanks. We'll take these into consideration 👍

**Comment by squallstar** [comment]
@seromenho I think you forgot to commit one of your templates because the handlebars template has been overwritten by my pull request [here](https://github.com/Fliplet/fliplet-widget-app-security/commit/39e9aa6ffb68fab724f7ea67560ae39d678a6e44#diff-2ca5b8b3a9b568c07aae93997db3ed35) and now the pages don't autocomplete anymore.

**Comment by seromenho** [comment]
@squallstar fixed here: https://github.com/Fliplet/fliplet-widget-app-security/pull/3

**Pull request merged**
